apiVersion: v1
data:
  JVB_STUN_SERVERS: {{ $.Values.JVB_STUN_SERVERS }}
  PUBLIC_URL: {{ ((gt (len $.Values.ingress.hosts) 0) | ternary (print "https://" ($.Values.ingress.hosts | first)) $.Values.PUBLIC_URL) | required "One of PUBLIC_URL or ingress.hosts must be provided" }}
  TZ: {{ $.Values.TZ }}
kind: ConfigMap
metadata:
  labels:
    scope: jitsi
  name: jitsi-config
  namespace: {{ $.Values.namespace }}
